# Generated by Django 6.0.2 on 2026-02-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('event_type', models.CharField(blank=True, default='', max_length=128)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField()),
                ('signature', models.CharField(blank=True, default='', max_length=512)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='received', max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'event_type'], name='webhooks_we_source_5a0d87_idx'), models.Index(fields=['external_id'], name='webhooks_we_externa_3bfef9_idx'), models.Index(fields=['received_at'], name='webhooks_we_receive_c9d554_idx')],
            },
        ),
    ]
